import { Download, LockKeyhole, LogOut, Plus, Save, Trash2 } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type DocumentKind = 'battery' | 'solar' | 'cctv' | 'invoice';
type Line = { description: string; hsn: string; quantity: number; unit: string; rate: number; gstRate: number };
type DocumentState = { number: string; date: string; validUntil: string; customer: string; address: string; gstin: string; contact: string; subject: string; introduction: string; notes: string; terms: string; handledBy: string; lines: Line[] };

const kinds: { id: DocumentKind; label: string; title: string }[] = [
  { id: 'battery', label: 'Battery', title: 'Battery quotation' }, { id: 'solar', label: 'Solar', title: 'Solar quotation' },
  { id: 'cctv', label: 'CCTV', title: 'CCTV quotation' }, { id: 'invoice', label: 'Tax invoice', title: 'Tax invoice' },
];
const today = () => new Date().toISOString().slice(0, 10);
const defaults = (kind: DocumentKind): DocumentState => {
  const common = { number: `PLT/${kind === 'invoice' ? 'INV' : 'QTN'}/001`, date: today(), validUntil: '', customer: '', address: '', gstin: '', contact: '', handledBy: 'PowerLink Technologies', notes: 'Thank you for choosing PowerLink Technologies.', terms: 'Prices are inclusive of applicable taxes unless stated otherwise. Delivery and installation scope will be confirmed before dispatch.' };
  const presets: Record<DocumentKind, Pick<DocumentState, 'subject' | 'introduction' | 'lines'>> = {
    battery: { subject: 'Proposal for battery backup solution', introduction: 'We are pleased to submit our quotation for a reliable power-backup solution as discussed.', lines: [{ description: 'Tubular battery', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 18 }, { description: 'Battery installation and commissioning', hsn: '', quantity: 1, unit: 'Job', rate: 0, gstRate: 18 }] },
    solar: { subject: 'Proposal for solar power system', introduction: 'We are pleased to submit our proposal for a dependable solar solution designed for your requirement.', lines: [{ description: 'Solar PV module', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 12 }, { description: 'Solar inverter', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 12 }, { description: 'Installation and commissioning', hsn: '', quantity: 1, unit: 'Job', rate: 0, gstRate: 18 }] },
    cctv: { subject: 'Proposal for CCTV surveillance system', introduction: 'We are pleased to submit our quotation for the following security and surveillance equipment.', lines: [{ description: 'CCTV dome camera', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 18 }, { description: 'DVR / NVR', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 18 }, { description: 'Cabling and installation', hsn: '', quantity: 1, unit: 'Job', rate: 0, gstRate: 18 }] },
    invoice: { subject: '', introduction: '', lines: [{ description: 'Power solution / supply and installation', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 18 }] },
  };
  return { ...common, ...presets[kind] };
};
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value);
const amount = (line: Line) => line.quantity * line.rate;
const words = (value: number) => value === 0 ? 'Zero rupees only' : `${new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(value)} rupees only`;

export default function Invoice() {
  const ownerEmail = 'powerlink2008@gmail.com';
  const [authenticated, setAuthenticated] = useState(false);
  const [checkingSession, setCheckingSession] = useState(true);
  const [error, setError] = useState('');
  const [kind, setKind] = useState<DocumentKind>('battery');
  const [document, setDocument] = useState<DocumentState>(() => { const saved = localStorage.getItem('plt-document-battery'); return saved ? JSON.parse(saved) : defaults('battery'); });
  const isInvoice = kind === 'invoice';
  const subtotal = useMemo(() => document.lines.reduce((total, line) => total + amount(line), 0), [document.lines]);
  const tax = useMemo(() => document.lines.reduce((total, line) => total + amount(line) * line.gstRate / 100, 0), [document.lines]);
  const total = subtotal + tax;
  useEffect(() => { localStorage.setItem(`plt-document-${kind}`, JSON.stringify(document)); }, [kind, document]);
  useEffect(() => { fetch('/api/invoice-session', { credentials: 'include' }).then(response => response.json()).then(data => setAuthenticated(Boolean(data.authenticated))).catch(() => setAuthenticated(false)).finally(() => setCheckingSession(false)); }, []);
  const changeKind = (next: DocumentKind) => { const saved = localStorage.getItem(`plt-document-${next}`); setKind(next); setDocument(saved ? JSON.parse(saved) : defaults(next)); };
  const setField = <K extends keyof DocumentState>(key: K, value: DocumentState[K]) => setDocument(old => ({ ...old, [key]: value }));
  const setLine = (index: number, key: keyof Line, value: string) => setDocument(old => ({ ...old, lines: old.lines.map((line, i) => i === index ? { ...line, [key]: ['description', 'hsn', 'unit'].includes(key) ? value : Math.max(0, Number(value)) } : line) }));
  const login = async (event: FormEvent) => { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); try { const response = await fetch('/api/invoice-login', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); const data = await response.json(); if (!response.ok) return setError(data.error ?? 'Unable to sign in.'); setAuthenticated(true); } catch { setError('Unable to reach the secure login service.'); } };
  const logout = async () => { await fetch('/api/invoice-logout', { method: 'POST', credentials: 'include' }).catch(() => undefined); setAuthenticated(false); };

  if (checkingSession) return <main className="grid min-h-screen place-items-center bg-[#10252a] px-4 font-sans text-stone-200"><p className="text-sm">Checking owner access…</p></main>;
  if (!authenticated) return <main className="min-h-screen bg-[#10252a] px-4 py-20 font-sans text-stone-100"><section className="mx-auto max-w-md border border-white/15 bg-[#17353a] p-8 shadow-[0_24px_55px_rgba(0,0,0,.3)]"><div className="grid h-12 w-12 place-items-center bg-[#d7a545] text-[#10252a]"><LockKeyhole className="h-5 w-5" /></div><h1 className="mt-8 text-3xl font-semibold tracking-tight">PowerLink documents</h1><p className="mt-3 text-sm leading-6 text-stone-300">Private workspace for quotations, tax invoices, and PDF-ready documents.</p><form onSubmit={login} className="mt-8"><label className="block text-sm font-medium">Owner email<input readOnly required type="email" name="email" autoComplete="email" value={ownerEmail} className="mt-2 w-full border border-white/25 bg-white/10 px-3 py-3 text-stone-300 outline-none" /></label><label className="mt-4 block text-sm font-medium">Password<input required type="password" name="password" autoComplete="current-password" autoFocus className="mt-2 w-full border border-white/25 bg-white/10 px-3 py-3 text-white outline-none transition focus:border-[#d7a545]" /></label>{error && <p className="mt-3 text-sm text-amber-300">{error}</p>}<button className="mt-6 w-full bg-[#d7a545] px-4 py-3 text-sm font-bold text-[#10252a] transition hover:bg-[#e4ba65]">Sign in</button></form><a href="/" className="mt-5 block text-center text-sm text-stone-300 hover:text-white">Back to website</a></section></main>;

  const documentLabel = kinds.find(item => item.id === kind)!.title;
  return <main className="min-h-screen bg-[#e9e7e1] font-sans text-slate-900 print:bg-white"><header className="border-b border-slate-300 bg-[#f8f7f3] print:hidden"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-4"><a href="/" className="text-sm font-bold tracking-tight text-[#10363a]">POWERLINK TECHNOLOGIES</a><div className="flex items-center gap-2"><button onClick={logout} className="inline-flex items-center gap-2 px-3 py-2 text-sm font-medium text-slate-600 hover:text-slate-950"><LogOut className="h-4 w-4" />Lock</button><button onClick={() => window.print()} className="inline-flex items-center gap-2 bg-[#10363a] px-4 py-2 text-sm font-semibold text-white hover:bg-[#17484d]"><Download className="h-4 w-4" />Save as PDF</button></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 p-5 lg:grid-cols-[280px_minmax(0,1fr)] print:block print:p-0"><aside className="print:hidden"><div className="border border-slate-300 bg-[#f8f7f3] p-3"><p className="px-2 pb-3 text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Document format</p>{kinds.map(item => <button key={item.id} onClick={() => changeKind(item.id)} className={`block w-full px-3 py-3 text-left text-sm font-semibold transition ${kind === item.id ? 'bg-[#10363a] text-white' : 'text-slate-700 hover:bg-slate-200'}`}>{item.label}</button>)}</div><div className="mt-4 border border-slate-300 bg-[#f8f7f3] p-5"><p className="text-sm font-semibold">Your draft is saved here</p><p className="mt-2 text-sm leading-5 text-slate-600">Each format keeps its own editable draft on this device.</p><button onClick={() => setDocument(defaults(kind))} className="mt-5 text-sm font-semibold text-[#10363a] hover:underline">Start this format again</button></div></aside>
      <div className="min-w-0"><div className="mb-5 flex items-center justify-between print:hidden"><h1 className="text-xl font-semibold tracking-tight">{documentLabel}</h1><span className="inline-flex items-center gap-2 text-sm text-slate-500"><Save className="h-4 w-4" />Saved automatically</span></div><section className="invoice-sheet mx-auto max-w-5xl bg-white p-5 shadow-[0_18px_42px_rgba(15,23,42,.13)] sm:p-9 print:max-w-none print:p-9 print:shadow-none"><div className="border-t-[7px] border-[#92b9c2] pt-5"><header className="grid gap-6 border-b border-slate-400 pb-5 md:grid-cols-[1.1fr_.9fr]"><div><div className="inline-grid h-11 w-11 place-items-center border-2 border-[#10363a] text-sm font-black text-[#10363a]">PLT</div><h2 className="mt-3 text-2xl font-bold tracking-tight text-[#10363a]">POWERLINK TECHNOLOGIES</h2><p className="mt-1 max-w-md text-xs leading-5 text-slate-600">#62, 4th Cross, Muninanjappa Layout, Behind IBP Petrol Bunk,<br />Ramamurthy Nagar, Bangalore – 560016 · 9901893191 · powerlink2008@gmail.com</p></div><div className="border border-slate-300 bg-[#edf4f5] p-4"><h3 className="text-center text-base font-bold uppercase tracking-wide text-[#10363a]">{isInvoice ? 'Tax Invoice' : 'Quotation'}</h3><div className="mt-3 grid grid-cols-[98px_1fr] gap-y-2 text-xs"><span className="font-semibold">{isInvoice ? 'Invoice no.' : 'Reference no.'}</span><input value={document.number} onChange={e => setField('number', e.target.value)} className="min-w-0 border-b border-slate-400 bg-transparent outline-none" /><span className="font-semibold">Date</span><input type="date" value={document.date} onChange={e => setField('date', e.target.value)} className="min-w-0 border-b border-slate-400 bg-transparent outline-none" />{!isInvoice && <><span className="font-semibold">Valid until</span><input type="date" value={document.validUntil} onChange={e => setField('validUntil', e.target.value)} className="min-w-0 border-b border-slate-400 bg-transparent outline-none" /><span className="font-semibold">Handled by</span><input value={document.handledBy} onChange={e => setField('handledBy', e.target.value)} className="min-w-0 border-b border-slate-400 bg-transparent outline-none" /></>}</div></div></header>
        <div className="my-6 grid gap-5 md:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#50747a]">{isInvoice ? 'Buyer (bill to)' : 'To'}</p><input value={document.customer} onChange={e => setField('customer', e.target.value)} placeholder="Customer / company name" className="mt-2 w-full border-b border-slate-400 py-1 text-lg font-bold outline-none placeholder:font-normal" /><textarea value={document.address} onChange={e => setField('address', e.target.value)} placeholder="Address" className="mt-2 min-h-20 w-full resize-none border-b border-slate-300 py-1 text-sm leading-5 outline-none" /></div><div className="md:border-l md:border-slate-200 md:pl-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#50747a]">Customer details</p><input value={document.contact} onChange={e => setField('contact', e.target.value)} placeholder="Contact number / email" className="mt-2 w-full border-b border-slate-300 py-2 text-sm outline-none" /><input value={document.gstin} onChange={e => setField('gstin', e.target.value)} placeholder="GSTIN (optional)" className="mt-2 w-full border-b border-slate-300 py-2 text-sm outline-none" /></div></div>
        {!isInvoice && <div className="mb-6"><input value={document.subject} onChange={e => setField('subject', e.target.value)} className="w-full border-b border-slate-400 py-2 text-sm font-bold outline-none" /><textarea value={document.introduction} onChange={e => setField('introduction', e.target.value)} className="mt-3 min-h-14 w-full resize-none border-b border-slate-200 py-2 text-sm leading-6 text-slate-600 outline-none" /></div>}
        <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-xs"><thead className="bg-[#c6dde0] text-slate-800"><tr><th className="w-10 border border-slate-400 p-2">Sl.</th><th className="border border-slate-400 p-2">Description of goods / service</th>{isInvoice && <th className="w-20 border border-slate-400 p-2">HSN/SAC</th>}<th className="w-16 border border-slate-400 p-2">GST</th><th className="w-16 border border-slate-400 p-2">Qty</th><th className="w-14 border border-slate-400 p-2">Unit</th><th className="w-24 border border-slate-400 p-2">Rate</th><th className="w-28 border border-slate-400 p-2 text-right">Amount</th><th className="w-8 border border-slate-400 p-2 print:hidden"></th></tr></thead><tbody>{document.lines.map((line, index) => <tr key={index}><td className="border border-slate-300 p-2 align-top">{index + 1}</td><td className="border border-slate-300 p-1"><input value={line.description} onChange={e => setLine(index, 'description', e.target.value)} className="w-full bg-transparent p-1 outline-none" /></td>{isInvoice && <td className="border border-slate-300 p-1"><input value={line.hsn} onChange={e => setLine(index, 'hsn', e.target.value)} className="w-full bg-transparent p-1 outline-none" /></td>}<td className="border border-slate-300 p-1"><input min="0" type="number" value={line.gstRate} onChange={e => setLine(index, 'gstRate', e.target.value)} className="w-full bg-transparent p-1 outline-none" /></td><td className="border border-slate-300 p-1"><input min="0" type="number" value={line.quantity} onChange={e => setLine(index, 'quantity', e.target.value)} className="w-full bg-transparent p-1 outline-none" /></td><td className="border border-slate-300 p-1"><input value={line.unit} onChange={e => setLine(index, 'unit', e.target.value)} className="w-full bg-transparent p-1 outline-none" /></td><td className="border border-slate-300 p-1"><input min="0" type="number" value={line.rate} onChange={e => setLine(index, 'rate', e.target.value)} className="w-full bg-transparent p-1 outline-none" /></td><td className="border border-slate-300 p-2 text-right font-semibold">{money(amount(line))}</td><td className="border border-slate-300 p-1 text-center print:hidden"><button disabled={document.lines.length === 1} onClick={() => setDocument(old => ({ ...old, lines: old.lines.filter((_, i) => i !== index) }))} className="text-slate-400 hover:text-red-600 disabled:opacity-30"><Trash2 className="h-3.5 w-3.5" /></button></td></tr>)}</tbody></table></div>
        <button onClick={() => setDocument(old => ({ ...old, lines: [...old.lines, { description: '', hsn: '', quantity: 1, unit: 'Nos', rate: 0, gstRate: 18 }] }))} className="mt-3 inline-flex items-center gap-1.5 text-sm font-semibold text-[#10363a] hover:underline print:hidden"><Plus className="h-4 w-4" />Add line item</button>
        <div className="mt-7 grid gap-6 md:grid-cols-[1fr_290px]"><div>{isInvoice && <div className="border border-slate-300"><p className="border-b border-slate-300 bg-[#edf4f5] p-2 text-xs font-bold uppercase tracking-wide">Tax analysis</p><div className="grid grid-cols-3 gap-2 p-3 text-xs"><span>Taxable value</span><span className="text-right">CGST + SGST</span><b className="text-right">{money(subtotal)}</b><span>GST payable</span><span className="text-right">Split equally for local supply</span><b className="text-right">{money(tax)}</b></div></div>}<p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-[#50747a]">Terms & conditions</p><textarea value={document.terms} onChange={e => setField('terms', e.target.value)} className="mt-2 min-h-20 w-full resize-none border border-slate-300 p-3 text-xs leading-5 outline-none" /></div><div className="border-t-2 border-[#10363a] pt-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="mt-2 flex justify-between"><span>GST</span><b>{money(tax)}</b></div><div className="mt-3 flex justify-between border-t border-slate-400 pt-3 text-lg font-bold text-[#10363a]"><span>Total</span><span>{money(total)}</span></div></div></div>
        {isInvoice && <p className="mt-4 border-y border-slate-300 py-2 text-xs font-semibold">Amount chargeable (in words): {words(total)}</p>}
        <footer className="mt-8 grid gap-6 border-t border-slate-300 pt-5 text-xs text-slate-600 md:grid-cols-2"><div><p className="font-bold text-slate-800">Notes</p><textarea value={document.notes} onChange={e => setField('notes', e.target.value)} className="mt-2 min-h-14 w-full resize-none border-b border-slate-300 py-1 leading-5 outline-none" /></div><div className="self-end text-right"><p className="font-bold text-slate-800">for PowerLink Technologies</p><div className="mt-10 border-t border-slate-400 pt-2">Authorised signatory</div></div></footer>
      </div></section></div></div>
  </main>;
}
